### ISSUE TITLE
Uncaught exception 'ReflectionException'

### ISSUE THREAD

**Issue by stormwalkerec** [RemyJeancolas/slim-annotations-router#1]
Error message:
Uncaught exception 'ReflectionException' with message 'Class HomeController does not exist'

Here is my code:

in index.php:

```
$c['router'] = function() use ($app) {
    return new \Ergy\Slim\Annotations\Router($app,
        THEPATH.'/routes/', // Path to controller files, will be scanned recursively
        THEPATH.'/cache/' // Path to annotations router cache files, must be writeable by web server, if it doesn't exist, router will attempt to create it
    );
};
```

in routes folder:
homeController.php - contents:

```
<?php
/**
 * File /my/app/controllers/homeController.php
 * @RoutePrefix("/home")
 */
class HomeController
{
    /**
     * @Route("/hello/{name:[\w]+}", methods={"GET","POST"}, name="home.hello")
     */
    public function helloAction($name)
    {
        echo 'Hello '.$name.' !';
    }
}

```

Full error as shown by slim:

Uncaught exception 'ReflectionException' with message 'Class HomeController does not exist' in /var/www/clients/client1/web2/web/vendor/ergy/slim-annotations-router/src/Router.php:199
Stack trace:
#0 /var/www/clients/client1/web2/web/vendor/ergy/slim-annotations-router/src/Router.php(199): ReflectionClass-&gt;__construct('HomeController')
#1 /var/www/clients/client1/web2/web/vendor/ergy/slim-annotations-router/src/Router.php(147): Ergy\Slim\Annotations\Router-&gt;_parseFile('/var/www/client...')
#2 /var/www/clients/client1/web2/web/vendor/ergy/slim-annotations-router/src/Router.php(61): Ergy\Slim\Annotations\Router-&gt;_generateRoutes()
#3 /var/www/clients/client1/web2/web/index.php(37): Ergy\Slim\Annotations\Router-&gt;__construct(Object(Slim\App), '/var/www/client...', '/var/www/client...')
#4 /var/www/clients/client1/web2/web/vendor/pimple/pimple/src/Pimple/Container.php(113): {closure}(Object(Slim\Container))
#5 /var/www/clients/client1/web2/web/vendor/slim/slim/Slim/Container.php(266): Pimple\Container-&gt;offsetGet('r in <b>/var/www/clients/client1/web2/web/vendor/ergy/slim-annotations-router/src/Router.php</b> on line <b>199</b>

**Comment by RemyJeancolas** [comment]
Hi,
To work properly, classes loaded by the router **must** be found by your autoloader.
Can you load your class by using `$controller = new HomeController();` ?
If not, this problem occurs either because your autoloader can't find the class, or because you don't use an autoloader.

**Comment by stormwalkerec** [comment]
Im new to slim 3. was previously using fatfree

Heres my complete index file and how I am loading everything:

```
<?php
ini_set('display_errors', 1);
//ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require_once('core_globals.php');
//require_once('interface_functions.php');
require dirname(__FILE__).'/vendor/autoload.php';

$app = new \Slim\App();

$c = $app->getContainer();

$c['errorHandler'] = function ($c) {
    return function ($request, $response, $exception) use ($c) {
        return $c['response']->withStatus(500)
            ->withHeader('Content-Type', 'text/html')
            ->write('Something went wrong!');
    };
};
$c['notFoundHandler'] = function ($c) {
    return function ($request, $response) use ($c) {
        return $c['response']
            ->withStatus(404)
            ->withHeader('Content-Type', 'text/html')
            ->write('Page not found');
    };
};
$c['router'] = function() use ($app) {
    return new \Ergy\Slim\Annotations\Router($app,
        THEPATH.'/routes/', // Path to controller files, will be scanned recursively
        THEPATH.'/cache/' // Path to annotations router cache files, must be writeable by web server, if it doesn't exist, router will attempt to create it
    );
};

$checkProxyHeaders = true;
$trustedProxies = ['10.0.0.1', '10.0.0.2'];
$app->add(new RKA\Middleware\IpAddress($checkProxyHeaders, $trustedProxies));

$controller = new HomeController();

$app->get('/ip', function ($request, $response, $args) {
    $ipAddress = $request->getAttribute('ip_address');
    echo "IP - ".$ipAddress;
});

$app->run();
```

And composer has auto downloaded and created the vendor file I included.

So the AutoLoader should be working ?

$controller = new HomeController();

Gives me an error as it is not part of the vendor directory
Does your system autoload from the controller folder ? because it is then not working... or I have to do something extra

Under the cache folder, the two files are created, but they are empty bar the top displaying the time generated.

As is, if i delete the homeController.php file, everything works 100%. The moment I upload the file, I get that message.

**Comment by RemyJeancolas** [comment]
Ok so it's a composer autoloader issue.
Just to explain, composer autoloader is effectively loaded, but it only works for files under the _vendor_ directory.
To add specific files to composer autoloader, just add (or edit) a _composer.json_ file at the root of your project and add your classes into it. Then execute `composer update` to force autoloader refresh.
For example if your top directory looks like this :

```
controllers/ // <-- your controllers folder
vendor/ // <-- vendor folder created by composer
index.php // <-- main application file
composer.json // <-- file containing your project's informations and your custom autoloader(s)
... // other files
```

If your _controllers/_ dir contains a file named _homeController.php_, your _composer.json_ file should look like this :

```
{
    "require": {
        // Classes included via composer
    },
    // Maybe other stuff...
    "autoload": {
        "psr-4": {
          "MyProject\\Controllers\\": "controllers/"
        }
    }
}
```

The important part is the `autoload` node, it indicates to composer to look for classes under namespace `MyProject\Controller` in the directory `controllers/` of your application.
To work properly, you should add a namespace in your `homeController.php` file, in this case add `namespace MyProject\Controllers;` under the `<?php` line.

You can get more information by Googling _composer autoload own classes_.

**Comment by stormwalkerec** [comment]
OK, that works 100%

Only bummer is that every time I add a new controller, I need to composer dump-autoload -o

How do you autoload without having to do that ? are you using another autoloader ?

**Comment by RemyJeancolas** [comment]
If you add new controllers in your _controllers/_ dir and if they all use the same namespace, you **don't** need to reload composer autoloader (I use my router every day for months and never had this issue). In the others cases you will indeed need to reload composer autoloader, there's no magic to avoid that.
Happy coding :wink:
